// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evidencijaRVS.Evidencija.DAL;

#nullable disable

namespace Evidencija.DAL.Migrations
{
    [DbContext(typeof(EvidencijaDBcontext))]
    partial class EvidencijaDBcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("evidencijaRVS.Evidencija.DAL.Models.Korisnik", b =>
                {
                    b.Property<int>("korisnik_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("korisnik_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("korisnik_id"));

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("adresa");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ime");

                    b.Property<string>("lozinka")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("lozinka");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("prezime");

                    b.HasKey("korisnik_id");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("evidencijaRVS.Evidencija.DAL.Models.Pregled", b =>
                {
                    b.Property<int>("pregled_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pregled_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pregled_id"));

                    b.Property<int>("anamneza_id")
                        .HasColumnType("int")
                        .HasColumnName("anamneza_id");

                    b.Property<DateTime>("datumpregleda")
                        .HasColumnType("datetime2")
                        .HasColumnName("datumpregleda");

                    b.Property<string>("dijagnoza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dijagnoza");

                    b.Property<bool>("hitanslucaj")
                        .HasColumnType("bit")
                        .HasColumnName("hitanslucaj");

                    b.Property<string>("prioritetpregleda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("prioritetpregleda");

                    b.Property<decimal>("telesna_temperatura")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("telesna_temperatura");

                    b.Property<string>("terapija")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("terapija");

                    b.HasKey("pregled_id");

                    b.ToTable("pregled");
                });

            modelBuilder.Entity("evidencijaRVS.Evidencija.DAL.Models.anamneza", b =>
                {
                    b.Property<int>("anamneza_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("anamneza_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("anamneza_id"));

                    b.Property<bool>("Primaolekove")
                        .HasColumnType("bit")
                        .HasColumnName("Primaolekove");

                    b.Property<string>("Razlogdolaska")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Razlogdolaska");

                    b.Property<string>("Smestaj")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Smestaj");

                    b.Property<string>("Urinistolica")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Urinistolica");

                    b.Property<DateTime>("datumunosa")
                        .HasColumnType("datetime2")
                        .HasColumnName("datumunosa");

                    b.Property<string>("ishrana")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ishrana");

                    b.Property<string>("kojelekove")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kojelekove");

                    b.Property<string>("ranijebolovala")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ranijebolovala");

                    b.Property<int>("zivotinja_id")
                        .HasColumnType("int")
                        .HasColumnName("zivotinja_id");

                    b.HasKey("anamneza_id");

                    b.ToTable("anamneza");
                });

            modelBuilder.Entity("evidencijaRVS.Evidencija.DAL.Models.lek", b =>
                {
                    b.Property<int>("lek_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("lek_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lek_id"));

                    b.Property<string>("doza")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("doza");

                    b.Property<string>("nazivleka")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nazivleka");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.HasKey("lek_id");

                    b.ToTable("lek");
                });

            modelBuilder.Entity("evidencijaRVS.Evidencija.DAL.Models.terapija", b =>
                {
                    b.Property<int>("terapija_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("terapija_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("terapija_id"));

                    b.Property<int>("kolicina")
                        .HasColumnType("int")
                        .HasColumnName("kolicina");

                    b.Property<int>("lek_id")
                        .HasColumnType("int")
                        .HasColumnName("lek_id");

                    b.Property<string>("napomena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("napomena");

                    b.Property<int>("pregled_id")
                        .HasColumnType("int")
                        .HasColumnName("pregled_id");

                    b.HasKey("terapija_id");

                    b.ToTable("terapija");
                });

            modelBuilder.Entity("evidencijaRVS.Evidencija.DAL.Models.zivotinje", b =>
                {
                    b.Property<int>("zivotinja_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("zivotinja_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("zivotinja_id"));

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ime");

                    b.Property<int>("korisnik_id")
                        .HasColumnType("int")
                        .HasColumnName("korisnik_id");

                    b.Property<string>("namena")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("namena");

                    b.Property<string>("pol")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("pol");

                    b.Property<int>("starost")
                        .HasColumnType("int")
                        .HasColumnName("starost");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("vrsta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("vrsta");

                    b.HasKey("zivotinja_id");

                    b.ToTable("zivotinje");
                });
#pragma warning restore 612, 618
        }
    }
}
